### ISSUE TITLE
Bug: Syntax Highlight can break Meta-Bind inline buttons

### ISSUE THREAD

**Issue by alaestor** [mayurankv/Obsidian-Code-Styler#300]
Behavioral incompatibility under certain circumstances

## Describe the bug
Styler breaks some inline [meta-bind](https://github.com/mProjectsCode/obsidian-meta-bind-plugin) buttons when inline code styling is enabled.

### Steps to reproduce
Enable reader mode with "Syntax Highlight Inline Code" enabled
```md
---
opt1: 1
opt2: 2
---

`INPUT[inlineSelect(option(1,1),option(2,2),option(3,3)):opt1]` `INPUT[inlineSelect(option(1,1),option(2,2),option(3,3)):opt2]`
````

### Expected behaviour

With syntax highlighting disabled, the buttons appear as normal (albeit with a background from Styling)
![Image](https://github.com/user-attachments/assets/ada378cc-e74d-4043-90fe-e17cc9aee76a)

### Current behaviour

With syntax highlighting enabled, the second button breaks itself into a multi-line list of the display texts
![Image](https://github.com/user-attachments/assets/98a751ab-27ec-4be6-aa73-5c3f10fd3126)

This only occurs with multiple buttons.

### Environment

- Plugin Version: 1.1.7
- Obsidian Version:  1.7.7
- Platform:  Desktop
- OS:  NixOS
- Theme:  tested with defaults (not reflective of screenshots)
- CSS Snippets: tested with none

**Comment by alaestor** [comment]
Duplicate of #242 ... (not sure why I didn't see it the first time I searched...)

**Comment by mayurankv** [comment]
Thanks for closing the issue! As an update, I am working on Code Styler right now after a little hiatus. I'm carrying out a refactor which should make resolving this issue easier!

**Comment by mayurankv** [comment]
This is fixed and will be included in the next release!

**Comment by pplucky** [comment]
Hello.

First of all, thanks a lot for your great plugin.

I just updated manually the plugin (downloaded raw versions of [main.js](https://github.com/mayurankv/Obsidian-Code-Styler/blob/main/main.js), [styles.css](https://github.com/mayurankv/Obsidian-Code-Styler/blob/main/styles.css), [manifest.json](https://github.com/mayurankv/Obsidian-Code-Styler/blob/main/manifest.json) to my vault folder) and issue doesn't seem fixed to me. Already closed and reopened notes and also vault.

Editing/preview mode:
![Image](https://github.com/user-attachments/assets/4d481a9e-abf2-4ba3-86d0-f0cb3e7672a6)

Reading mode:

![Image](https://github.com/user-attachments/assets/6941d35d-a68f-43a3-8b1f-ce79f70b84a6)

As per others, if I disable "Syntax Highlight Inline Code", it all works perfectly in both modes.

Can you please check?

**Comment by mayurankv** [comment]
Hiya, are you sure you used the `refactor` branch? The files you've downloaded appear to be from the `main` branch. Note that this isn't finished so the live preview mode may appear quite jarring, but the meta bind content should work fine! As far as I'm aware, the only inline content MetaBind exposes is the `BUTTON` syntax. If there's anything else, please let me know and I can add that.

Otherwise I think that it is indeed resolved. Try downloading the refactor branch files instead and let me know!

**Comment by pplucky** [comment]
> Hello.
> 
> First of all, thanks a lot for your great plugin.
> 
> I just updated manually the plugin (downloaded raw versions of [main.js](https://github.com/mayurankv/Obsidian-Code-Styler/blob/main/main.js), [styles.css](https://github.com/mayurankv/Obsidian-Code-Styler/blob/main/styles.css), [manifest.json](https://github.com/mayurankv/Obsidian-Code-Styler/blob/main/manifest.json) to my vault folder) and issue doesn't seem fixed to me. Already closed and reopened notes and also vault.
> 
> Editing/preview mode: ![Image](https://github.com/user-attachments/assets/4d481a9e-abf2-4ba3-86d0-f0cb3e7672a6)
> 
> Reading mode:
> 
> ![Image](https://github.com/user-attachments/assets/6941d35d-a68f-43a3-8b1f-ce79f70b84a6)
> 
> As per others, if I disable "Syntax Highlight Inline Code", it all works perfectly in both modes.
> 
> Can you please check?

Still experiencing this issue, even after updating to [latest version](https://github.com/mayurankv/Obsidian-Code-Styler/releases/tag/1.1.7).

As far as I understood, this should've been fixed already, right?

@mayurankv Please let me how I can help to get this fixed.
