### ISSUE TITLE
Bug: Scrollbars appear for some themes (and can scroll)

### ISSUE THREAD

**Issue by mayurankv** [mayurankv/Obsidian-Code-Styler#58]
## Describe the bug

Scrollbars appear in some cases for some themes.

### Steps to reproduce

````markdown
```python
line 1
line 2
line 3
```
````

and theme 'Atom'.

### Expected behaviour

No scrolling or scrollbar occurs.

### Current behaviour

Scrolling possible and scrollbar visible.

### Environment

- Plugin Version: 1.0.2
- Obsidian Version:  1.3.5
- Platform:  Desktop
- OS:  macOS

**Comment by fareloz** [comment]
Hi! I reported this bug on reddit.
Here is the video I recorded to show the bug: 
https://github.com/mayurankv/Obsidian-Code-Styler/assets/7237969/47f284ca-78c6-4975-9016-be2948de25df

As you can see I disabled my css adjustments and set default theme. Then I restarted the app and you can see the scrollbar appears on the left of each block.
But is the page is long and I scroll down, starting from some block the scrollbar doesn't appear. And if I go up the scrollbar goes away even for previous blocks

**Comment by mayurankv** [comment]
Can you try the new update and see whether the issue still occurs?

**Comment by fareloz** [comment]
> Can you try the new update and see whether the issue still occurs?

It does, although the scrollbar is much thinner. And usually in the first block of the page

**Comment by fareloz** [comment]
Just found the way to reproduce. I created an empty vault with default settings and installed only the code styler plugin. I set header to always visible in the settings of the plugin. 
The way to reproduce is to increase Zoom Level of Obsidian to exactly 110% and switch around the notes

**Comment by mayurankv** [comment]
So closing and reopening the note doesn't make the issue go away?

**Comment by mayurankv** [comment]
I actually still can't replicate it. Could you give me the contents of a note which has the issue?

**Comment by fareloz** [comment]
[ScrollbarBug.zip](https://github.com/mayurankv/Obsidian-Code-Styler/files/12290860/ScrollbarBug.zip)
Here is the test vault with plugin installed, heading set to always visible, default view - reading, zoom level - 110%. My screen resolution is 1920x1080 if matters.

**Comment by mayurankv** [comment]
I'm really sorry about this, I still can't seem to replicate this. Are you using macOS? What is your obsidian version?

**Comment by mayurankv** [comment]
For reference, this is what I get using your vault:

https://github.com/mayurankv/Obsidian-Code-Styler/assets/69591376/fecd3f4d-62a0-4b14-8e6a-4a634e86ce13

**Comment by Dimava** [comment]
I did have the problem in 1.0.2, doesn't appear in 1.0.3 for me

**Comment by fareloz** [comment]
> For reference, this is what I get using your vault:
> 
>  No.Replication.mp4

Please try to open right sidebar and also try to switch between notes, not only one note with only one code block

**Comment by mayurankv** [comment]
I tried to replicate with both sidebars open, and switching between notes. Also changing zooms. Unfortunately, I still couldn't replicate. I'll try and test on windows asap.

**Comment by Dimava** [comment]
BTW jumping is annoying, it there a way to remove it
At least by `transition-duration: 0s`

**Comment by mayurankv** [comment]
Thank you @Dimava ! I think its very likely a windows effect then as I'm still unable to replicate it at all. Will update this thread when I've had a look on Windows

**Comment by mayurankv** [comment]
What is jumping sorry?

**Comment by fareloz** [comment]
> What is jumping sorry?

When the code block doesn't appear entirely on note opening, but slides down from the heading

**Comment by mayurankv** [comment]
I'd rather not release a new version till I'm sure the issue is fixed. Would either of you be willing to try out the latest version directly from github and see whether the current behaviour is satisfactory regarding the jumping?

It prevents the sliding motion but there is still a flashing effect as the codeblock is initially rendered as obsidian would before the markdown processor processes it. Is this better?

**Comment by Dimava** [comment]
Scrollbars are fixed, I've checked.

@mayurankv actually I think you should just `code { max-height: unset !important; }` (i.e. removing it everywhere) and allow it to height itself
That completely removes jumping it seems, try it please

**Comment by mayurankv** [comment]
Hi @Dimava, are you aware of the folding functionality when you click on the header? That functionality is why I need to set max height. If the jumping is completely unusable I could remove the folding animation and just have it as an instant collapse but I'd rather have both working! Wouldn't unsetting max height break the folding when clicking the header?

**Comment by Dimava** [comment]
@mayurankv well, it would, but the problem is that when you use it on *open* code, you'll get scrollbars.
E.g. if I have wrapping code I get scrollbar for the number of wraps lines

Feel free to use max-height during animation, it's fine, but please remove it in opened state

**Comment by mayurankv** [comment]
Oooh, letting it animate and then removing it, that's very doable I think, I'll have a play.

**Comment by mayurankv** [comment]
Please update to 1.0.4 and check whether the scrollbar issue persists? Some changes were made to eliminate the max-height being used outside of animations as suggested by @Dimava. These changes should also have eliminated the jumping. I'll close this issue for now as I'm pretty confident it should be resolved but please do comment if that isn't the case.

**Comment by fareloz** [comment]
It is fixed on my side
